@host = https://localhost:7097/api

### Get Films
GET {{host}}/films

### Get Film
GET {{host}}/films/3

###Create Film
POST {{host}}/films
Content-Type: application/json

{
    "Title" : "The Godfather Part II",
    "Year" : 1974,
    "Length" : 202,
    "RatingScore" : 9.0,
    "Mpaa" : "R",
    "Actors" : [
        {
            "FirstName" : "Al",
            "LastName" : "Pacino",
            "Age" : 83,
            "Gender" : 1,
            "ImbLink" : "https://www.imdb.com/name/nm0000199/"
        },
        {
            "FirstName" : "Robert",
            "LastName" : "De Niro",
            "Age" : 84,
            "Gender" : 1,
            "ImbLink" : "https://www.imdb.com/name/nm0000134/"
        }
    ]
}

###Update Film
PUT {{host}}/films/9
Content-Type: application/json

{
    "Title" : "The Godfather Part II",
    "Year" : 1974,
    "Length" : 202,
    "RatingScore" : 9.2,
    "Mpaa" : "R",
    "Actors" : [
        {
            "FirstName" : "Al",
            "LastName" : "Pacino",
            "Age" : 83,
            "Gender" : 1,
            "ImbLink" : "https://www.imdb.com/name/nm0000199/"
        }
    ]
}


###Delete Film
DELETE {{host}}/films/10


###Get Actors
GET {{host}}/films/3/actors