// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSGettingStartedSW.Console.DataContext;


#nullable disable

namespace PSGettingStartedSW.Migrations
{
    [DbContext(typeof(FilmDbContext))]
    [Migration("20261006183941_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSGettingStartedSW.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int?>("FilmId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("ImbLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FilmId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Age = 64,
                            FilmId = 1,
                            FirstName = "Tim",
                            Gender = 1,
                            ImbLink = "https://www.imdb.com/name/nm0000209/",
                            LastName = "Robbins"
                        },
                        new
                        {
                            Id = 2,
                            Age = 80,
                            FilmId = 1,
                            FirstName = "Morgan",
                            Gender = 1,
                            ImbLink = "https://www.imdb.com/name/nm0000151/",
                            LastName = "Freeman"
                        },
                        new
                        {
                            Id = 3,
                            Age = 50,
                            FilmId = 2,
                            FirstName = "Christian",
                            Gender = 1,
                            ImbLink = "https://www.imdb.com/name/nm0000288/",
                            LastName = "Bale"
                        },
                        new
                        {
                            Id = 4,
                            Age = 93,
                            FilmId = 3,
                            FirstName = "Marlon",
                            Gender = 1,
                            ImbLink = "https://www.imdb.com/name/nm0000008/",
                            LastName = "Brando"
                        },
                        new
                        {
                            Id = 5,
                            Age = 83,
                            FilmId = 3,
                            FirstName = "Al",
                            Gender = 1,
                            ImbLink = "https://www.imdb.com/name/nm0000199/",
                            LastName = "Pacino"
                        },
                        new
                        {
                            Id = 6,
                            Age = 73,
                            FilmId = 4,
                            FirstName = "John",
                            Gender = 1,
                            ImbLink = "https://www.imdb.com/name/nm0000237/",
                            LastName = "Travolta"
                        },
                        new
                        {
                            Id = 7,
                            Age = 71,
                            FilmId = 4,
                            FirstName = "Uma",
                            Gender = 0,
                            ImbLink = "https://www.imdb.com/name/nm0000235/",
                            LastName = "Thurman"
                        },
                        new
                        {
                            Id = 8,
                            Age = 84,
                            FilmId = 4,
                            FirstName = "Samuel L.",
                            Gender = 1,
                            ImbLink = "https://www.imdb.com/name/nm0000168/",
                            LastName = "Jackson"
                        });
                });

            modelBuilder.Entity("PSGettingStartedSW.Entities.Film", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Mpaa")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("RatingScore")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Films");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Length = 182,
                            Mpaa = "R",
                            RatingScore = 9.3000000000000007,
                            Title = "The Shawshank Redemption",
                            Year = 1994
                        },
                        new
                        {
                            Id = 2,
                            Length = 152,
                            Mpaa = "PG-13",
                            RatingScore = 9.0999999999999996,
                            Title = "The Dark Knight",
                            Year = 2008
                        },
                        new
                        {
                            Id = 3,
                            Length = 175,
                            Mpaa = "R",
                            RatingScore = 9.1999999999999993,
                            Title = "The Godfather",
                            Year = 1972
                        },
                        new
                        {
                            Id = 4,
                            Length = 154,
                            Mpaa = "R",
                            RatingScore = 8.8000000000000007,
                            Title = "Pulp",
                            Year = 1994
                        });
                });

            modelBuilder.Entity("PSGettingStartedSW.Entities.Actor", b =>
                {
                    b.HasOne("PSGettingStartedSW.Entities.Film", null)
                        .WithMany("Actors")
                        .HasForeignKey("FilmId");
                });

            modelBuilder.Entity("PSGettingStartedSW.Entities.Film", b =>
                {
                    b.Navigation("Actors");
                });
#pragma warning restore 612, 618
        }
    }
}
